homo:
  describe: this's a prod homo
datasource:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/homo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    databaseName: mysql
    driverName: com.mysql.cj.jdbc.Driver
    user: root
    password: root
  oracle:
    url: jdbc:oracle://127.0.0.1:1521/homo
    databaseName: mysql
    driverName: com.mysql.cj.jdbc.Driver
    user: root
    password: root
server:
  port: 80
  servlet:
    context-path: /homo
spring:
  cache:
    cache-names: homo
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s