homo:
  describe: this's a test homo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/homo?serverTimezone=GMT%2B8
    name: com.mysql.cj.jdbc.Driver
    user: root
    password: root
server:
  port: 8081
  servlet:
    context-path: /
